name: my workflow
on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  eslint-reviewdog-job:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup Node.js
        uses: actions/setup-node@v4
      - name: install eslint
        run: npm install eslint
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check # Change reporter.
          eslint_flags: "--config eslint.config.js"